// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdO7NAZzdZd8KY3jc8LeNGgWJ_iUDS73Y',
    appId: '1:975925310656:web:626fbdae3619a0d6b2e925',
    messagingSenderId: '975925310656',
    projectId: 'flutter-easyenglish',
    authDomain: 'flutter-easyenglish.firebaseapp.com',
    storageBucket: 'flutter-easyenglish.firebasestorage.app',
    measurementId: 'G-WZ68T8M9XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Jl0_bw7ZwaxmEdHNU9CnE4v1w7-wNiQ',
    appId: '1:975925310656:android:ff3f60543b838330b2e925',
    messagingSenderId: '975925310656',
    projectId: 'flutter-easyenglish',
    storageBucket: 'flutter-easyenglish.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ic66Exdx-0tw2KmEPdZMLooeKvgmrxQ',
    appId: '1:975925310656:ios:894e2aceabf063c8b2e925',
    messagingSenderId: '975925310656',
    projectId: 'flutter-easyenglish',
    storageBucket: 'flutter-easyenglish.firebasestorage.app',
    androidClientId: '975925310656-8dtahr5q159n88gjoruf9rq7n71r9o29.apps.googleusercontent.com',
    iosClientId: '975925310656-4510dmhj37bsuejeq1cc1ml9da7eibjg.apps.googleusercontent.com',
    iosBundleId: 'com.easyenglish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ic66Exdx-0tw2KmEPdZMLooeKvgmrxQ',
    appId: '1:975925310656:ios:894e2aceabf063c8b2e925',
    messagingSenderId: '975925310656',
    projectId: 'flutter-easyenglish',
    storageBucket: 'flutter-easyenglish.firebasestorage.app',
    androidClientId: '975925310656-8dtahr5q159n88gjoruf9rq7n71r9o29.apps.googleusercontent.com',
    iosClientId: '975925310656-4510dmhj37bsuejeq1cc1ml9da7eibjg.apps.googleusercontent.com',
    iosBundleId: 'com.easyenglish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdO7NAZzdZd8KY3jc8LeNGgWJ_iUDS73Y',
    appId: '1:975925310656:web:87204edddba78e2db2e925',
    messagingSenderId: '975925310656',
    projectId: 'flutter-easyenglish',
    authDomain: 'flutter-easyenglish.firebaseapp.com',
    storageBucket: 'flutter-easyenglish.firebasestorage.app',
    measurementId: 'G-TJ8EXQ6341',
  );

}